# Generated by Django 4.2.6 on 2023-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_avatar_remove_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="I'm using Tweeter!", max_length=360),
        ),
    ]
