# Generated by Django 4.2.6 on 2023-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_slug'),
        ('user', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_posts',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
